modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="visual_recipe_editor"
version="1.0.0"
displayName="可视化配方编写"
# logoFile="pack.png"
authors="Xiaoyu_2009"
description='''
支持多种工作方块的可视化配方编写
'''

[[dependencies.visual_recipe_editor]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.visual_recipe_editor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"